/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author jeron
 */
import Main.*;
import javax.swing.JOptionPane;
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Cuadrado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnLadoCuadrado = new javax.swing.JSpinner();
        btnAreaCuadrado = new javax.swing.JButton();
        btnPerimetroCuadrado = new javax.swing.JButton();
        Circulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spnRadioCirculo = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        btnAreaCirculo = new javax.swing.JButton();
        btnPerimetroCirculo = new javax.swing.JButton();
        TrianguloRectangulo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spnBaseTriangulo = new javax.swing.JSpinner();
        spnAlturaTriangulo = new javax.swing.JSpinner();
        btnAreaTriangulo = new javax.swing.JButton();
        btnTipoTriangulo = new javax.swing.JButton();
        btnHipotenusaTriangulo = new javax.swing.JButton();
        Rectangulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spnBaseRectangulo = new javax.swing.JSpinner();
        spnAlturaRectangulo = new javax.swing.JSpinner();
        btnAreaRectangulo = new javax.swing.JButton();
        btnPerimetroRectangulo = new javax.swing.JButton();

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 150));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cuadrado.setBackground(new java.awt.Color(204, 204, 255));
        Cuadrado.setPreferredSize(new java.awt.Dimension(250, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cuadrado");

        jLabel6.setText("Lado");

        spnLadoCuadrado.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        btnAreaCuadrado.setBackground(new java.awt.Color(204, 204, 204));
        btnAreaCuadrado.setText("Area");
        btnAreaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCuadradoActionPerformed(evt);
            }
        });

        btnPerimetroCuadrado.setBackground(new java.awt.Color(204, 204, 204));
        btnPerimetroCuadrado.setText("Perimetro");
        btnPerimetroCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CuadradoLayout = new javax.swing.GroupLayout(Cuadrado);
        Cuadrado.setLayout(CuadradoLayout);
        CuadradoLayout.setHorizontalGroup(
            CuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuadradoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuadradoLayout.createSequentialGroup()
                .addGroup(CuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CuadradoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnLadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuadradoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnAreaCuadrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnPerimetroCuadrado)))
                .addGap(31, 31, 31))
        );
        CuadradoLayout.setVerticalGroup(
            CuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(CuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnLadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaCuadrado)
                    .addComponent(btnPerimetroCuadrado))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel5.add(Cuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 250, 140));

        Circulo.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Circulo");

        spnRadioCirculo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel5.setText("Radio");

        btnAreaCirculo.setBackground(new java.awt.Color(204, 204, 204));
        btnAreaCirculo.setText("Area");
        btnAreaCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCirculoActionPerformed(evt);
            }
        });

        btnPerimetroCirculo.setBackground(new java.awt.Color(204, 204, 204));
        btnPerimetroCirculo.setText("Perimetro");
        btnPerimetroCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCirculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CirculoLayout = new javax.swing.GroupLayout(Circulo);
        Circulo.setLayout(CirculoLayout);
        CirculoLayout.setHorizontalGroup(
            CirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CirculoLayout.createSequentialGroup()
                .addGroup(CirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CirculoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnAreaCirculo)
                        .addGap(34, 34, 34)
                        .addComponent(btnPerimetroCirculo))
                    .addGroup(CirculoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)
                        .addGap(45, 45, 45)
                        .addComponent(spnRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CirculoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        CirculoLayout.setVerticalGroup(
            CirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(CirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaCirculo)
                    .addComponent(btnPerimetroCirculo))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.add(Circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 140));

        TrianguloRectangulo.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Triangulo rectangulo");

        jLabel9.setText("Base");

        jLabel10.setText("Altura");

        spnBaseTriangulo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        spnAlturaTriangulo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        btnAreaTriangulo.setBackground(new java.awt.Color(204, 204, 204));
        btnAreaTriangulo.setText("Area");
        btnAreaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTrianguloActionPerformed(evt);
            }
        });

        btnTipoTriangulo.setBackground(new java.awt.Color(204, 204, 204));
        btnTipoTriangulo.setText("Tipo");
        btnTipoTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoTrianguloActionPerformed(evt);
            }
        });

        btnHipotenusaTriangulo.setBackground(new java.awt.Color(204, 204, 204));
        btnHipotenusaTriangulo.setText("Hipotenusa");
        btnHipotenusaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHipotenusaTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TrianguloRectanguloLayout = new javax.swing.GroupLayout(TrianguloRectangulo);
        TrianguloRectangulo.setLayout(TrianguloRectanguloLayout);
        TrianguloRectanguloLayout.setHorizontalGroup(
            TrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrianguloRectanguloLayout.createSequentialGroup()
                .addGroup(TrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrianguloRectanguloLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4))
                    .addGroup(TrianguloRectanguloLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(TrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(TrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnAlturaTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(spnBaseTriangulo))))
                .addGap(31, 31, 31))
            .addGroup(TrianguloRectanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAreaTriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHipotenusaTriangulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TrianguloRectanguloLayout.setVerticalGroup(
            TrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrianguloRectanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(TrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnBaseTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnAlturaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaTriangulo)
                    .addComponent(btnTipoTriangulo)
                    .addComponent(btnHipotenusaTriangulo))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel5.add(TrianguloRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 250, 140));

        Rectangulo.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Rectangulo");

        jLabel7.setText("Base");

        jLabel8.setText("Altura");

        spnBaseRectangulo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        spnAlturaRectangulo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        btnAreaRectangulo.setBackground(new java.awt.Color(204, 204, 204));
        btnAreaRectangulo.setText("Area");
        btnAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRectanguloActionPerformed(evt);
            }
        });

        btnPerimetroRectangulo.setBackground(new java.awt.Color(204, 204, 204));
        btnPerimetroRectangulo.setText("Perimetro");
        btnPerimetroRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroRectanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RectanguloLayout = new javax.swing.GroupLayout(Rectangulo);
        Rectangulo.setLayout(RectanguloLayout);
        RectanguloLayout.setHorizontalGroup(
            RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RectanguloLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnAlturaRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(spnBaseRectangulo))
                .addGap(33, 33, 33))
            .addGroup(RectanguloLayout.createSequentialGroup()
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RectanguloLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnAreaRectangulo)
                        .addGap(34, 34, 34)
                        .addComponent(btnPerimetroRectangulo))
                    .addGroup(RectanguloLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        RectanguloLayout.setVerticalGroup(
            RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RectanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnBaseRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAlturaRectangulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAreaRectangulo)
                    .addComponent(btnPerimetroRectangulo))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.add(Rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 250, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCirculoActionPerformed
        // TODO add your handling code here:
        double Radio =(double)this.spnRadioCirculo.getValue();
        Circulo circulo=new Circulo(Radio);
        double Area=circulo.calcularArea();
        JOptionPane.showMessageDialog(null, "Area: "+Area
                    , "Area del Circulo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAreaCirculoActionPerformed

    private void btnPerimetroCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCirculoActionPerformed
        // TODO add your handling code here:
        double Radio =(double)this.spnRadioCirculo.getValue();
        Circulo circulo=new Circulo(Radio);
        double Perimetro=circulo.calcularPerimetro();
        JOptionPane.showMessageDialog(this, "Perimetro: "+Perimetro
                    , "Perimetro del Circulo", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnPerimetroCirculoActionPerformed

    private void btnAreaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCuadradoActionPerformed
        // TODO add your handling code here:
        double lado =(double)this.spnLadoCuadrado.getValue();
        Cuadrado cuadrado=new Cuadrado(lado);
        double Area=cuadrado.calcularArea();
        JOptionPane.showMessageDialog(this, "Area: "+Area
                    , "Area del Cuadrado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAreaCuadradoActionPerformed

    private void btnPerimetroCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCuadradoActionPerformed
        // TODO add your handling code here:
        double lado =(double)this.spnLadoCuadrado.getValue();
        Cuadrado cuadrado=new Cuadrado(lado);
        double Perimetro=cuadrado.calcularPerimetro();
        JOptionPane.showMessageDialog(this, "Perimetro: "+Perimetro
                    , "Perimetro del Cuadrado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnPerimetroCuadradoActionPerformed

    private void btnAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRectanguloActionPerformed
        double Base =(double)this.spnBaseRectangulo.getValue();
        double Altura =(double)this.spnAlturaRectangulo.getValue();
        Rectangulo rectangulo=new Rectangulo(Base, Altura);
        double Area=rectangulo.calcularArea();
        JOptionPane.showMessageDialog(this, "Area: "+Area
                    , "Area del Rectangulo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAreaRectanguloActionPerformed

    private void btnPerimetroRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroRectanguloActionPerformed
        // TODO add your handling code here:
        double Base =(double)this.spnBaseRectangulo.getValue();
        double Altura =(double)this.spnAlturaRectangulo.getValue();
        Rectangulo rectangulo=new Rectangulo(Base, Altura);
        double Perimetro=rectangulo.calcularPerimetro();
        JOptionPane.showMessageDialog(this, "Perimetro: "+Perimetro
                    , "Perimetro del Rectangulo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnPerimetroRectanguloActionPerformed

    private void btnAreaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTrianguloActionPerformed
        // TODO add your handling code here:
        double Base =(double)this.spnBaseTriangulo.getValue();
        double Altura =(double)this.spnAlturaTriangulo.getValue();
        TrianguloRectangulo triangulo=new TrianguloRectangulo(Base, Altura);
        double Area=triangulo.calcularArea();
        JOptionPane.showMessageDialog(this, "Area: "+Area
                    , "Area del Triangulo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAreaTrianguloActionPerformed

    private void btnHipotenusaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHipotenusaTrianguloActionPerformed
        // TODO add your handling code here:
        double Base =(double)this.spnBaseTriangulo.getValue();
        double Altura =(double)this.spnAlturaTriangulo.getValue();
        TrianguloRectangulo triangulo=new TrianguloRectangulo(Base, Altura);
        double Hipotenusa=triangulo.calcularHipotenusa();
        JOptionPane.showMessageDialog(this, "Hipotenusa: "+Hipotenusa
                    , "Hipotenusa del Triangulo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHipotenusaTrianguloActionPerformed

    private void btnTipoTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoTrianguloActionPerformed
        // TODO add your handling code here:
        double Base =(double)this.spnBaseTriangulo.getValue();
        double Altura =(double)this.spnAlturaTriangulo.getValue();
        TrianguloRectangulo triangulo=new TrianguloRectangulo(Base, Altura);
        triangulo.determinarTipoTriangulo();
        
    }//GEN-LAST:event_btnTipoTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Circulo;
    private javax.swing.JPanel Cuadrado;
    private javax.swing.JPanel Rectangulo;
    private javax.swing.JPanel TrianguloRectangulo;
    private javax.swing.JButton btnAreaCirculo;
    private javax.swing.JButton btnAreaCuadrado;
    private javax.swing.JButton btnAreaRectangulo;
    private javax.swing.JButton btnAreaTriangulo;
    private javax.swing.JButton btnHipotenusaTriangulo;
    private javax.swing.JButton btnPerimetroCirculo;
    private javax.swing.JButton btnPerimetroCuadrado;
    private javax.swing.JButton btnPerimetroRectangulo;
    private javax.swing.JButton btnTipoTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSpinner spnAlturaRectangulo;
    private javax.swing.JSpinner spnAlturaTriangulo;
    private javax.swing.JSpinner spnBaseRectangulo;
    private javax.swing.JSpinner spnBaseTriangulo;
    private javax.swing.JSpinner spnLadoCuadrado;
    private javax.swing.JSpinner spnRadioCirculo;
    // End of variables declaration//GEN-END:variables
}
